services:
  clickhouse:
    image: clickhouse/clickhouse-server
    user: "101:101"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_UID=101
      - CLICKHOUSE_GID=101
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=clickhouse_password

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=your_mysql_root_password
      - MYSQL_DATABASE=timefly
      - MYSQL_USER=timefly_user
      - MYSQL_PASSWORD=your_mysql_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  clickhouse_data:
  mysql_data: